In [1]:
import pandas as pd

In [2]:
learn_df = pd.read_csv("modal_experiment_v1_training_norming_candidates_with_comprehension.csv")

# throw out wh-question and individual scenarios that performed worst during norming
to_keep = ["T1","T3","T5","T7","T9","T12"]
learn_df = learn_df[learn_df["item_id"].isin(to_keep)].reset_index(drop=True)

learn_df.head()

,index,phase,item_id,domain,training_flavor,syntax,D_status,E_status,temporal_orientation,order_pair_id,...,whole_scenario_response_options,expected_context_D,expected_context_E,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation,notes,comprehension_question,comprehension_option_A,comprehension_option_B,comprehension_correct
0,0,Training,T1,Museum entrance,Root/deontic,Declarative,D+,E unspecified / not ruled out,future eventive,TR,...,Yes | No,D+,E should not be ruled out,Expected root/deontic interpretation,Expected non-epistemic interpretation,Positive-only training candidate. Context-only...,Why is Lina visiting the history museum?,For a class project,For a family trip,A
1,1,Training,T1,Museum entrance,Epistemic,Declarative,D unspecified,E+,past perfect / present progressive or stative,TE,...,Yes | No,D should be 'The story does not say',E+,Expected non-deontic interpretation,Expected epistemic interpretation,Positive-only training candidate. Context-only...,Why is Lina visiting the history museum?,For a class project,For a family trip,A
2,4,Training,T3,Community center,Root/deontic,Declarative,D+,E unspecified / not ruled out,future eventive,TR,...,Yes | No,D+,E should not be ruled out,Expected root/deontic interpretation,Expected non-epistemic interpretation,Positive-only training candidate. Context-only...,Which areas does Nora's membership include?,Only the climbing area,The swimming pool and climbing area,B
3,5,Training,T3,Community center,Epistemic,Declarative,D unspecified,E+,past perfect / present progressive or stative,TE,...,Yes | No,D should be 'The story does not say',E+,Expected non-deontic interpretation,Expected epistemic interpretation,Positive-only training candidate. Context-only...,What does the front desk know about Nora's act...,"She chose either swimming or climbing, but not...",She chose swimming,A
4,8,Training,T5,Parking,Root/deontic,Yes/no inversion,D+,E unspecified / not ruled out,future eventive,TR,...,Yes | No,D+,E should not be ruled out,Expected root/deontic interpretation,Expected non-epistemic interpretation,Positive-only training candidate. Context-only...,What kind of event is Omar attending?,A museum exhibition,A concert,B

In [3]:
learn_df["D_status"] = learn_df["D_status"].map({"D+": 1, "D unspecified": 0, "D-": -1})
learn_df["E_status"] = learn_df["E_status"].map({"E+": 1, "E unspecified / not ruled out": 0, "E-": -1})

learn_df["E_status"].tolist()

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]

In [4]:
order1_df = learn_df[[
            "phase",
            "item_id",
            "domain",
            "training_flavor",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_1",
            "context_order_1",
            "functional_auxiliary_target",
            "lexical_adjective_target",
            "comprehension_question",
            "comprehension_option_A",
            "comprehension_option_B",
            "comprehension_correct"
            ]].rename(columns={
                "order_1":"order",
                "context_order_1":"context_order"
                })
order1_df["order_group"] = (order1_df.reset_index().index % 4) < 2

order2_df = learn_df[[
            "phase",
            "item_id",
            "domain",
            "training_flavor",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_2",
            "context_order_2",
            "functional_auxiliary_target",
            "lexical_adjective_target",
            "comprehension_question",
            "comprehension_option_A",
            "comprehension_option_B",
            "comprehension_correct"]].rename(columns={
                "order_2":"order",
                "context_order_2":"context_order"
                })
order2_df["order_group"] = (order1_df.reset_index().index % 4) >= 2
learn_df = pd.concat([order1_df, order2_df])
learn_df["order_group"] = learn_df["order_group"].apply(int).apply(str)

print(order1_df["order_group"].tolist())
print(order2_df["order_group"].tolist())

print(learn_df["order"].tolist())
learn_df.groupby(["order_group", "training_flavor"])["order"].value_counts()

[True, True, False, False, True, True, False, False, True, True, False, False]
[False, False, True, True, False, False, True, True, False, False, True, True]
['N-D', 'N-E', 'N-D', 'N-E', 'N-D', 'N-E', 'N-D', 'N-E', 'N-D', 'N-E', 'N-D', 'N-E', 'D-N', 'E-N', 'D-N', 'E-N', 'D-N', 'E-N', 'D-N', 'E-N', 'D-N', 'E-N', 'D-N', 'E-N']

order_group  training_flavor  order
0            Epistemic        E-N      3
                              N-E      3
             Root/deontic     D-N      3
                              N-D      3
1            Epistemic        E-N      3
                              N-E      3
             Root/deontic     D-N      3
                              N-D      3
Name: count, dtype: int64

In [5]:

functional = learn_df[[
            "phase",
            "item_id",
            "domain",
            "training_flavor",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_group",
            "order",
            "context_order",
            "functional_auxiliary_target",
            "comprehension_question",
            "comprehension_option_A",
            "comprehension_option_B",
            "comprehension_correct"
            ]].rename(columns={
                "functional_auxiliary_target":"alien_target_response",
                })
functional["modal_type"] = "functional"

lexical = learn_df[[
            "phase",
            "item_id",
            "domain",
            "training_flavor",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_group",
            "order",
            "context_order",
            "lexical_adjective_target",
            "comprehension_question",
            "comprehension_option_A",
            "comprehension_option_B",
            "comprehension_correct"
            ]].rename(columns={
                "lexical_adjective_target":"alien_target_response",
                })
lexical["modal_type"] = "lexical"

learn_df = pd.concat([functional, lexical])
learn_df.head()

,phase,item_id,domain,training_flavor,D_status,E_status,temporal_orientation,order_group,order,context_order,alien_target_response,comprehension_question,comprehension_option_A,comprehension_option_B,comprehension_correct,modal_type
0,Training,T1,Museum entrance,Root/deontic,1,0,future eventive,1,N-D,Lina is visiting a history museum tomorrow for...,Lina dax use the side entrance tomorrow.,Why is Lina visiting the history museum?,For a class project,For a family trip,A,functional
1,Training,T1,Museum entrance,Epistemic,0,1,past perfect / present progressive or stative,1,N-E,Lina visited a history museum this morning for...,Lina dax have used the side entrance.,Why is Lina visiting the history museum?,For a class project,For a family trip,A,functional
2,Training,T3,Community center,Root/deontic,1,0,future eventive,0,N-D,Nora is going to the community center this aft...,Nora dax use the pool this afternoon.,Which areas does Nora's membership include?,Only the climbing area,The swimming pool and climbing area,B,functional
3,Training,T3,Community center,Epistemic,0,1,past perfect / present progressive or stative,0,N-E,Nora is at the community center right now. The...,Nora dax be swimming now.,What does the front desk know about Nora's act...,"She chose either swimming or climbing, but not...",She chose swimming,A,functional
4,Training,T5,Parking,Root/deontic,1,0,future eventive,1,N-D,Omar is driving to a concert tomorrow. Omar's ...,Dax Omar park in the west lot tomorrow? — Yes.,What kind of event is Omar attending?,A museum exhibition,A concert,B,functional

In [6]:
learn_df["comprehension_correct"] = learn_df.apply(
    lambda x: x["comprehension_option_A"] if x["comprehension_correct"] == "A" else x["comprehension_option_B"],
    axis=1
)

learn_df["question_response"] = learn_df["alien_target_response"].apply(
    lambda x: x.split(" — ")[1] if " — " in x else ""
)
learn_df["alien_target_response"] = learn_df["alien_target_response"].apply(
    lambda x: x.split(" — ")[0]
)

learn_df["group"] = learn_df.apply(
    lambda x: "D->E_" + x["modal_type"] if x["training_flavor"] == "Root/deontic" else "E->D_" + x["modal_type"],
    axis=1
) + "_" + learn_df["order_group"]


learn_df.to_csv("exp1_learning_stimulus.csv")
learn_df.head()

,phase,item_id,domain,training_flavor,D_status,E_status,temporal_orientation,order_group,order,context_order,alien_target_response,comprehension_question,comprehension_option_A,comprehension_option_B,comprehension_correct,modal_type,question_response,group
0,Training,T1,Museum entrance,Root/deontic,1,0,future eventive,1,N-D,Lina is visiting a history museum tomorrow for...,Lina dax use the side entrance tomorrow.,Why is Lina visiting the history museum?,For a class project,For a family trip,For a class project,functional,,D->E_functional_1
1,Training,T1,Museum entrance,Epistemic,0,1,past perfect / present progressive or stative,1,N-E,Lina visited a history museum this morning for...,Lina dax have used the side entrance.,Why is Lina visiting the history museum?,For a class project,For a family trip,For a class project,functional,,E->D_functional_1
2,Training,T3,Community center,Root/deontic,1,0,future eventive,0,N-D,Nora is going to the community center this aft...,Nora dax use the pool this afternoon.,Which areas does Nora's membership include?,Only the climbing area,The swimming pool and climbing area,The swimming pool and climbing area,functional,,D->E_functional_0
3,Training,T3,Community center,Epistemic,0,1,past perfect / present progressive or stative,0,N-E,Nora is at the community center right now. The...,Nora dax be swimming now.,What does the front desk know about Nora's act...,"She chose either swimming or climbing, but not...",She chose swimming,"She chose either swimming or climbing, but not...",functional,,E->D_functional_0
4,Training,T5,Parking,Root/deontic,1,0,future eventive,1,N-D,Omar is driving to a concert tomorrow. Omar's ...,Dax Omar park in the west lot tomorrow?,What kind of event is Omar attending?,A museum exhibition,A concert,A concert,functional,Yes.,D->E_functional_1

In [7]:
learn_df.groupby(["group", "training_flavor", "modal_type"])["order"].value_counts()

group              training_flavor  modal_type  order
D->E_functional_0  Root/deontic     functional  D-N      3
                                                N-D      3
D->E_functional_1  Root/deontic     functional  D-N      3
                                                N-D      3
D->E_lexical_0     Root/deontic     lexical     D-N      3
                                                N-D      3
D->E_lexical_1     Root/deontic     lexical     D-N      3
                                                N-D      3
E->D_functional_0  Epistemic        functional  E-N      3
                                                N-E      3
E->D_functional_1  Epistemic        functional  E-N      3
                                                N-E      3
E->D_lexical_0     Epistemic        lexical     E-N      3
                                                N-E      3
E->D_lexical_1     Epistemic        lexical     E-N      3
                                                N-E      3
Name: count, dtype: int64

In [8]:
test_df = pd.read_csv("modal_experiment_v1_stimulus_candidates_v8.csv")
test_df = test_df[test_df["phase"].isin(["Filler", "Critical Test"])]
test_df.head()

,phase,item_id,domain,direction_or_condition,D_status,E_status,deontic_support_type,epistemic_support_type,temporal_orientation,order_pair_id,...,context_only_epistemic_response_options,whole_scenario_response_options,expected_context_D,expected_context_E,expected_test_response_or_interpretation,notes,training_flavor,syntax,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation
24,Critical Test,C1,Zoo animal-care room,Root→Epistemic,D-,E+,explicit institutional restriction,open because relevant evidence is incomplete; ...,past perfect,P1,...,Yes | No,1–7 scale between the deontic and epistemic re...,D-,E+,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
25,Critical Test,C1,Zoo animal-care room,Epistemic→Root,D+,E-,explicit credential-based permission,strongly contradicted by a finalized and confi...,future eventive,P2,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E-,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
26,Critical Test,C2,University observatory,Root→Epistemic,D-,E+,explicit training-based restriction,open because Theo's current location is unknown,present progressive,P3,...,Yes | No,1–7 scale between the deontic and epistemic re...,D-,E+,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
27,Critical Test,C2,University observatory,Epistemic→Root,D+,E-,explicit certification-based permission,strongly contradicted by a finalized and confi...,future eventive,P1,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E-,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
28,Critical Test,C3,Student film studio,Root→Epistemic,D-,E+,explicit role-based restriction,open because the production record is incomplete,past perfect,P2,...,Yes | No,1–7 scale between the deontic and epistemic re...,D-,E+,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN

In [9]:
"""
We scored stimuli using different criteria by item type. Training and critical items were ranked by flavor discrimination, \(P(E\mid E\text{-target})-P(E\mid D\text{-target})\), preferring scenarios that strongly shifted toward the intended interpretation. Fillers were ranked for flavor neutrality, preferring \(P(E)\) close to .5 and minimal divergence between may and possible, while preserving an even balance of \(D^+E^+\) and \(D^-E^-\) fillers. We avoided selecting based on significance of individual sparse cells.
"""

to_throw = ["F2", "F5", "C2", "C5"]
test_df = test_df[~test_df["item_id"].isin(to_throw)].reset_index()
test_df.head()

,index,phase,item_id,domain,direction_or_condition,D_status,E_status,deontic_support_type,epistemic_support_type,temporal_orientation,...,context_only_epistemic_response_options,whole_scenario_response_options,expected_context_D,expected_context_E,expected_test_response_or_interpretation,notes,training_flavor,syntax,expected_whole_scenario_deontic_interpretation,expected_whole_scenario_epistemic_interpretation
0,24,Critical Test,C1,Zoo animal-care room,Root→Epistemic,D-,E+,explicit institutional restriction,open because relevant evidence is incomplete; ...,past perfect,...,Yes | No,1–7 scale between the deontic and epistemic re...,D-,E+,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
1,25,Critical Test,C1,Zoo animal-care room,Epistemic→Root,D+,E-,explicit credential-based permission,strongly contradicted by a finalized and confi...,future eventive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E-,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
2,28,Critical Test,C3,Student film studio,Root→Epistemic,D-,E+,explicit role-based restriction,open because the production record is incomplete,past perfect,...,Yes | No,1–7 scale between the deontic and epistemic re...,D-,E+,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
3,29,Critical Test,C3,Student film studio,Epistemic→Root,D+,E-,explicit badge-based permission,strongly contradicted by a locked and confirme...,future eventive,...,Yes | No,1–7 scale between the deontic and epistemic re...,D+,E-,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN
4,30,Critical Test,C4,Hotel rooftop lounge,Root→Epistemic,D-,E+,explicit room-category restriction,open because Jordan's current location is unknown,present stative,...,Yes | No,1–7 scale between the deontic and epistemic re...,D-,E+,Transfer predicts Accept; source-flavor-only i...,The same context order version should be used ...,NaN,NaN,NaN,NaN

In [10]:
test_df["direction"] = test_df["direction_or_condition"].apply(lambda x: "D->E" if x == "Root→Epistemic" else "E->D")

# duplicate fillers because both groups share same
fillers = test_df[test_df["phase"] == "Filler"].copy()
fillers["direction"] = "D->E"
test_df = pd.concat([test_df, fillers])

test_df.groupby(["phase"])["direction"].value_counts()

phase          direction
Critical Test  D->E         6
               E->D         6
Filler         D->E         6
               E->D         6
Name: count, dtype: int64

In [11]:
order1_df = test_df[[
            "phase",
            "item_id",
            "domain",
            "direction",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_1",
            "context_order_1",
            "functional_auxiliary_target",
            "lexical_adjective_target",
            ]].rename(columns={
                "order_1":"order",
                "context_order_1":"context_order"
                })
order1_df["order_group"] = (order1_df.reset_index().index % 4) < 2

order2_df = test_df[[
            "phase",
            "item_id",
            "domain",
            "direction",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_2",
            "context_order_2",
            "functional_auxiliary_target",
            "lexical_adjective_target"
            ]].rename(columns={
                "order_2":"order",
                "context_order_2":"context_order"
                })
order2_df["order_group"] = (order1_df.reset_index().index % 4) >= 2
test_df = pd.concat([order1_df, order2_df])
test_df["order_group"] = test_df["order_group"].apply(int).apply(str)

print(order1_df["order_group"].tolist())
print(order2_df["order_group"].tolist())

print(test_df["order"].tolist())
test_df.groupby(["order_group", "direction", "phase"])["order"].value_counts()

[True, True, False, False, True, True, False, False, True, True, False, False, True, True, False, False, True, True, False, False, True, True, False, False]
[False, False, True, True, False, False, True, True, False, False, True, True, False, False, True, True, False, False, True, True, False, False, True, True]
['N-E-D', 'D-N-E', 'D-N-E', 'E-N-D', 'N-E-D', 'D-N-E', 'D-N-E', 'E-N-D', 'N-E-D', 'D-N-E', 'E-N-D', 'N-E-D', 'D-N-E', 'N-E-D', 'D-N-E', 'N-E-D', 'D-N-E', 'E-N-D', 'D-N-E', 'N-E-D', 'D-N-E', 'N-E-D', 'D-N-E', 'E-N-D', 'E-D-N', 'N-D-E', 'N-D-E', 'D-E-N', 'E-D-N', 'N-D-E', 'N-D-E', 'D-E-N', 'E-D-N', 'N-D-E', 'D-E-N', 'E-D-N', 'N-D-E', 'E-D-N', 'N-D-E', 'E-D-N', 'N-D-E', 'D-E-N', 'N-D-E', 'E-D-N', 'N-D-E', 'E-D-N', 'N-D-E', 'D-E-N']

order_group  direction  phase          order
0            D->E       Critical Test  E-D-N    3
                                       D-N-E    2
                                       E-N-D    1
                        Filler         D-N-E    2
                                       E-D-N    1
                                       E-N-D    1
                                       N-D-E    1
                                       N-E-D    1
             E->D       Critical Test  N-D-E    3
                                       E-N-D    2
                                       N-E-D    1
                        Filler         N-D-E    2
                                       D-E-N    1
                                       D-N-E    1
                                       E-D-N    1
                                       N-E-D    1
1            D->E       Critical Test  N-E-D    3
                                       N-D-E    2
                                       D-E-N    1
                        Filler         N-D-E    2
                                       D-E-N    1
                                       D-N-E    1
                                       E-D-N    1
                                       N-E-D    1
             E->D       Critical Test  D-N-E    3
                                       D-E-N    2
                                       E-D-N    1
                        Filler         D-N-E    2
                                       E-D-N    1
                                       E-N-D    1
                                       N-D-E    1
                                       N-E-D    1
Name: count, dtype: int64

In [12]:
test_df["D_status"] = test_df["D_status"].map({"D+": 1, "D unspecified": 0, "D-": -1})
test_df["E_status"] = test_df["E_status"].map({"E+": 1, "E-": -1})

functional = test_df[[
            "phase",
            "item_id",
            "domain",
            "direction",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_group",
            "order",
            "context_order",
            "functional_auxiliary_target",
            ]].rename(columns={
                "functional_auxiliary_target":"alien_target_response",
                })
functional["modal_type"] = "functional"

lexical = test_df[[
            "phase",
            "item_id",
            "domain",
            "direction",
            "D_status",
            "E_status",
            "temporal_orientation",
            "order_group",
            "order",
            "context_order",
            "lexical_adjective_target"
            ]].rename(columns={
                "lexical_adjective_target":"alien_target_response",
                })
lexical["modal_type"] = "lexical"

test_df = pd.concat([functional, lexical])

test_df["group"] = test_df["direction"] + "_" + test_df["modal_type"] + "_" + test_df["order_group"]

test_df.head()

,phase,item_id,domain,direction,D_status,E_status,temporal_orientation,order_group,order,context_order,alien_target_response,modal_type,group
0,Critical Test,C1,Zoo animal-care room,D->E,-1,1,past perfect,1,N-E-D,Aisha is photographing exhibits at the zoo for...,Aisha dax have gone into the animal-care room.,functional,D->E_functional_1
1,Critical Test,C1,Zoo animal-care room,E->D,1,-1,future eventive,1,D-N-E,Aisha's volunteer credential permits her to wo...,Aisha dax work in the animal-care room tomorrow.,functional,E->D_functional_1
2,Critical Test,C3,Student film studio,D->E,-1,1,past perfect,0,D-N-E,The sound-mixing suite is reserved for post-pr...,Grace dax have gone into the sound-mixing suite.,functional,D->E_functional_0
3,Critical Test,C3,Student film studio,E->D,1,-1,future eventive,0,E-N-D,The locked shooting schedule assigns Grace to ...,Grace dax use the sound-mixing suite tomorrow ...,functional,E->D_functional_0
4,Critical Test,C4,Hotel rooftop lounge,D->E,-1,1,present stative,1,N-E-D,Jordan is attending a conference at a downtown...,Jordan dax be in the rooftop lounge now.,functional,D->E_functional_1

In [13]:
test_df.groupby(["group", "direction", "modal_type"])["order"].value_counts()

group              direction  modal_type  order
D->E_functional_0  D->E       functional  D-N-E    4
                                          E-D-N    4
                                          E-N-D    2
                                          N-D-E    1
                                          N-E-D    1
D->E_functional_1  D->E       functional  N-D-E    4
                                          N-E-D    4
                                          D-E-N    2
                                          D-N-E    1
                                          E-D-N    1
D->E_lexical_0     D->E       lexical     D-N-E    4
                                          E-D-N    4
                                          E-N-D    2
                                          N-D-E    1
                                          N-E-D    1
D->E_lexical_1     D->E       lexical     N-D-E    4
                                          N-E-D    4
                                          D-E-N    2
                                          D-N-E    1
                                          E-D-N    1
E->D_functional_0  E->D       functional  N-D-E    5
                                          E-N-D    2
                                          N-E-D    2
                                          D-E-N    1
                                          D-N-E    1
                                          E-D-N    1
E->D_functional_1  E->D       functional  D-N-E    5
                                          D-E-N    2
                                          E-D-N    2
                                          E-N-D    1
                                          N-D-E    1
                                          N-E-D    1
E->D_lexical_0     E->D       lexical     N-D-E    5
                                          E-N-D    2
                                          N-E-D    2
                                          D-E-N    1
                                          D-N-E    1
                                          E-D-N    1
E->D_lexical_1     E->D       lexical     D-N-E    5
                                          D-E-N    2
                                          E-D-N    2
                                          E-N-D    1
                                          N-D-E    1
                                          N-E-D    1
Name: count, dtype: int64

In [14]:
test_df.to_csv("exp1_test_stimulus.csv")