In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("context_only_results.csv")
print(df.shape)
df.head()

(3267, 24)

,Results.reception.time,MD5.hash.of.participant.s.IP.address,Controller.name,Order.number.of.item,Inner.element.number,Label,Latin.Square.Group,PennElementType,PennElementName,Parameter,...,item_id,judgement_flavour,modal_possibility,context,context_only_question,domain,temporal_orientation,order,group,Comments
0,1792890126,8462782bb9855a57698240eee5406687,PennController,2,0,consent,NaN,PennController,0,_Header_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1792890126,8462782bb9855a57698240eee5406687,PennController,2,0,consent,NaN,PennController,0,_Trial_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1792890126,8462782bb9855a57698240eee5406687,PennController,2,0,consent,NaN,PennController,0,_Header_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1792890126,8462782bb9855a57698240eee5406687,PennController,2,0,consent,NaN,PennController,0,_Trial_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1792890126,8462782bb9855a57698240eee5406687,PennController,3,0,background,NaN,PennController,1,_Header_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
results = df[(df["Label"] == "experimental-trial") & (df["Parameter"] == "Selection")]
results.head()

,Results.reception.time,MD5.hash.of.participant.s.IP.address,Controller.name,Order.number.of.item,Inner.element.number,Label,Latin.Square.Group,PennElementType,PennElementName,Parameter,...,item_id,judgement_flavour,modal_possibility,context,context_only_question,domain,temporal_orientation,order,group,Comments
59,1792890126,8462782bb9855a57698240eee5406687,PennController,30,0,experimental-trial,NaN,Selector,selection,Selection,...,T4,Epistemic,1,A friend checked the passenger list for the 3:...,Based on the <b>information</b> described in t...,Train,past perfect / present progressive or stative,E-N,1.0,yes;no;third
65,1792890126,8462782bb9855a57698240eee5406687,PennController,31,0,experimental-trial,NaN,Selector,selection,Selection,...,T5,Epistemic,0,Omar is driving to a concert tomorrow. Omar's ...,Based on the <b>information</b> described in t...,Parking,future eventive,N-D,1.0,yes;no;third
71,1792890126,8462782bb9855a57698240eee5406687,PennController,29,0,experimental-trial,NaN,Selector,selection,Selection,...,T3,Epistemic,1,Nora is at the community center right now. The...,Based on the <b>information</b> described in t...,Community center,past perfect / present progressive or stative,N-E,1.0,yes;no;third
77,1792890126,8462782bb9855a57698240eee5406687,PennController,27,0,experimental-trial,NaN,Selector,selection,Selection,...,T12,Deontic,0,Daniel is doing an experiment right now. Labs ...,According to the <b>rules or permissions</b> d...,College lab,past perfect / present progressive or stative,N-E,1.0,yes;no;third
83,1792890126,8462782bb9855a57698240eee5406687,PennController,33,0,experimental-trial,NaN,Selector,selection,Selection,...,T7,Deontic,1,Eli is taking an art workshop tomorrow. Eli's ...,According to the <b>rules or permissions</b> d...,Art studio,future eventive,N-D,1.0,yes;no;third

In [5]:
results["phase"] = results["item_id"].apply(lambda x: x[0])
results["phase"]

/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_11301/2704397132.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results["phase"] = results["item_id"].apply(lambda x: x[0])

59      T
65      T
71      T
77      T
83      T
       ..
3236    T
3242    T
3248    C
3254    T
3260    C
Name: phase, Length: 384, dtype: object

In [6]:
results["group"].value_counts()

group
1.0    48
2.0    48
3.0    48
4.0    48
5.0    48
6.0    48
7.0    48
8.0    48
Name: count, dtype: int64

In [7]:
results.groupby(["judgement_flavour", "modal_possibility"])["Value"].value_counts()

judgement_flavour  modal_possibility  Value
Deontic            -1                 no       42
                                      yes       4
                                      third     2
                   0                  third    34
                                      yes      11
                                      no        3
                   1                  yes      89
                                      no        4
                                      third     3
Epistemic          -1                 no       29
                                      yes      19
                   0                  yes      45
                                      no        3
                   1                  yes      67
                                      no       29
Name: count, dtype: int64

In [8]:
results.groupby(["judgement_flavour", "modal_possibility", "phase"])["Value"].value_counts()

judgement_flavour  modal_possibility  phase  Value
Deontic            -1                 C      no       29
                                             yes       2
                                             third     1
                                      F      no       13
                                             yes       2
                                             third     1
                   0                  T      third    34
                                             yes      11
                                             no        3
                   1                  C      yes      31
                                             no        1
                                      F      yes      15
                                             no        1
                                      T      yes      43
                                             third     3
                                             no        2
Epistemic          -1                 C      yes      18
                                             no       14
                                      F      no       15
                                             yes       1
                   0                  T      yes      45
                                             no        3
                   1                  C      no       20
                                             yes      12
                                      F      yes      16
                                      T      yes      39
                                             no        9
Name: count, dtype: int64

In [9]:
results.groupby(["item_id", "judgement_flavour", "modal_possibility"])["Value"].value_counts().reset_index().to_csv("context_only_grouped_results_flavour.csv")

In [10]:
df = pd.read_csv("whole_scenario_results.csv")
print(df.shape)
df.head()

(7250, 27)

,Results.reception.time,MD5.hash.of.participant.s.IP.address,Controller.name,Order.number.of.item,Inner.element.number,Label,Latin.Square.Group,PennElementType,PennElementName,Parameter,...,response,left_interpretation,right_interpretation,scale_order,domain,temporal_orientation,order,response_condition,response_syntax,Comments
0,1792971529,0c533fdb1e3adb6cc8efb0c4a4223043,PennController,2,0,consent,NaN,PennController,0,_Trial_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1792971529,0c533fdb1e3adb6cc8efb0c4a4223043,PennController,2,0,consent,NaN,PennController,0,_Header_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1792971529,0c533fdb1e3adb6cc8efb0c4a4223043,PennController,2,0,consent,NaN,PennController,0,_Header_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1792971529,0c533fdb1e3adb6cc8efb0c4a4223043,PennController,2,0,consent,NaN,PennController,0,_Trial_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1792971529,0c533fdb1e3adb6cc8efb0c4a4223043,PennController,3,0,background,NaN,PennController,1,_Trial_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
results = df[(df["Label"] == "experimental-trial") & (df["Parameter"] == "Selection")]
results["selected"] = results.apply(
    lambda x: x["left_interpretation"] if x["Value"] == "left" else x["right_interpretation"],
    axis=1
)

results.head()

/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_11301/3388229339.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results["selected"] = results.apply(

,Results.reception.time,MD5.hash.of.participant.s.IP.address,Controller.name,Order.number.of.item,Inner.element.number,Label,Latin.Square.Group,PennElementType,PennElementName,Parameter,...,left_interpretation,right_interpretation,scale_order,domain,temporal_orientation,order,response_condition,response_syntax,Comments,selected
57,1792971529,0c533fdb1e3adb6cc8efb0c4a4223043,PennController,34,0,experimental-trial,NaN,Selector,selection,Selection,...,The rules or permissions,The available information,deontic-epistemic,Art studio,past perfect / present progressive or stative,N-E,may,Declarative,left;right,The available information
63,1792971529,0c533fdb1e3adb6cc8efb0c4a4223043,PennController,24,0,experimental-trial,NaN,Selector,selection,Selection,...,The rules or permissions,The available information,deontic-epistemic,Hotel conference suite,past perfect,N-E-D,may,NaN,left;right,The available information
69,1792971529,0c533fdb1e3adb6cc8efb0c4a4223043,PennController,30,0,experimental-trial,NaN,Selector,selection,Selection,...,The rules or permissions,The available information,deontic-epistemic,Community center,past perfect / present progressive or stative,N-E,may,Declarative,left;right,The available information
75,1792971529,0c533fdb1e3adb6cc8efb0c4a4223043,PennController,13,0,experimental-trial,NaN,Selector,selection,Selection,...,The rules or permissions,The available information,deontic-epistemic,University observatory,future eventive,N-D-E,may,NaN,left;right,The rules or permissions
81,1792971529,0c533fdb1e3adb6cc8efb0c4a4223043,PennController,14,0,experimental-trial,NaN,Selector,selection,Selection,...,The rules or permissions,The available information,deontic-epistemic,Student film studio,past perfect,N-E-D,may,NaN,left;right,The rules or permissions

In [12]:
# Your current coding:
# future eventive = expected deontic
# everything else = expected epistemic
results["expected_flavour"] = results["temporal_orientation"].apply(
    lambda x: "deontic" if x == "future eventive" else "epistemic"
)

/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_11301/2268762262.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results["expected_flavour"] = results["temporal_orientation"].apply(

In [13]:
import scipy.stats

def binom_test(results, groups, value):
    arr = results.groupby(groups)[value].value_counts().reset_index().to_numpy().reshape(-1, 2, 3)
    d = []
    for i in range(arr.shape[0]):
        group_name = arr[i][0][0]
        assert group_name == arr[i][1][0]

        if arr[i][0][1] == "The available information":
            epistemic_count = arr[i][0][2]
            deontic_count = arr[i][1][2]
        else:
            epistemic_count = arr[i][1][2]
            deontic_count = arr[i][0][2]
    
        result = scipy.stats.binomtest(k=epistemic_count, n=epistemic_count + deontic_count, p=0.5, alternative='two-sided')
        d.append({
            groups: group_name, 
            "count": epistemic_count+deontic_count, 
            "epistemic_percent": epistemic_count/(epistemic_count+deontic_count),
            "p-value": result.pvalue,
            "significant": "True" if result.pvalue < 0.05 else "",
        })
    df = pd.DataFrame(d)
    return df

binom_test(results, "order", "selected")

   order  count  epistemic_percent       p-value significant
0    D-N     96           0.302083  1.322222e-04        True
1    E-N     96           0.864583  1.202072e-13        True
2    N-D     96           0.166667  2.074411e-11        True
3  N-D-E    252           0.492063  8.501542e-01
4    N-E     96           0.791667  7.319368e-09        True
5  N-E-D    260           0.376923  8.660440e-05        True

In [14]:
results["response_polarity"] = results["response"].apply(lambda x: " not " in x)

# binom_test(results, ["expected_flavour", "response_polarity"], "selected")
results.groupby(["expected_flavour", "response_polarity"])["selected"].value_counts()

/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_11301/3740433854.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results["response_polarity"] = results["response"].apply(lambda x: " not " in x)

expected_flavour  response_polarity  selected
deontic           False              The rules or permissions     221
                                     The available information     88
                  True               The rules or permissions      68
                                     The available information     39
epistemic         False              The available information    238
                                     The rules or permissions      93
                  True               The rules or permissions      88
                                     The available information     61
Name: count, dtype: int64

In [15]:
binom_test(results, "temporal_orientation", "selected")

,temporal_orientation,count,epistemic_percent,p-value,significant
0,future eventive,416,0.305288,1.282206e-15,True
1,past perfect,160,0.512500,8.126156e-01,
2,past perfect / present progressive or stative,192,0.828125,5.555881e-21,True
3,present progressive,81,0.444444,3.741744e-01,
4,present stative,47,0.468085,7.708670e-01,

In [16]:
binom_test(results, "response_syntax", "selected")

    response_syntax  count  epistemic_percent   p-value significant
0       Declarative    128           0.500000  1.000000
1       Wh-question    128           0.632812  0.003374        True
2  Yes/no inversion    128           0.460938  0.426439

In [17]:
binom_test(results[results["temporal_orientation"] == "future eventive"], "response_syntax", "selected")

    response_syntax  count  epistemic_percent       p-value significant
0       Declarative     64           0.093750  9.029019e-12        True
1       Wh-question     64           0.421875  2.604355e-01
2  Yes/no inversion     64           0.187500  4.566611e-07        True

In [18]:

binom_test(results[results["temporal_orientation"] != "future eventive"], "response_syntax", "selected")

    response_syntax  count  epistemic_percent       p-value significant
0       Declarative     64           0.906250  9.029019e-12        True
1       Wh-question     64           0.843750  1.996498e-08        True
2  Yes/no inversion     64           0.734375  2.268824e-04        True

In [19]:
results[(results["temporal_orientation"] == "future eventive") & (results["response_syntax"] == "Wh-question")
        ].groupby("item_id")["selected"].value_counts()

item_id  selected
T10      The rules or permissions     10
         The available information     5
T2       The rules or permissions     10
         The available information     5
T4       The available information    13
         The rules or permissions      4
T8       The rules or permissions     13
         The available information     4
Name: count, dtype: int64

In [20]:
binom_test(results[results["temporal_orientation"] == "future eventive"], "response_condition", "selected")

  response_condition  count  epistemic_percent       p-value significant
0                may    182           0.263736  1.343380e-10        True
1           possible    234           0.337607  7.625889e-07        True

In [21]:
binom_test(results[results["temporal_orientation"] != "future eventive"], "response_condition", "selected")

  response_condition  count  epistemic_percent       p-value significant
0                may    210           0.695238  1.509178e-08        True
1           possible    270           0.566667  3.297649e-02        True

In [23]:
from statsmodels.genmod.bayes_mixed_glm import BinomialBayesMixedGLM

df = results.copy()

# 1 = epistemic response, 0 = deontic response
df["epistemic_response"] = (
    df["selected"] == "The available information"
).astype(int)

# Make reference levels explicit:
# deontic target = reference
# may = reference
df["expected_flavor"] = pd.Categorical(
    df["expected_flavour"],
    categories=["deontic", "epistemic"]
)

df["response_condition"] = pd.Categorical(
    df["response_condition"],
    categories=["may", "possible"]
)
df["participant_id"] = df["MD5.hash.of.participant.s.IP.address"]


model = BinomialBayesMixedGLM.from_formula(
    "epistemic_response ~ C(expected_flavor) * C(response_condition)",
    {
        "participant": "0 + C(participant_id)",
        "item": "0 + C(item_id)"
    },
    df
)

fit = model.fit_vb()

print(fit.summary())

                                           Binomial Mixed GLM Results
================================================================================================================
                                                                  Type Post. Mean Post. SD   SD  SD (LB) SD (UB)
----------------------------------------------------------------------------------------------------------------
Intercept                                                            M    -1.1616   0.0754
C(expected_flavor)[T.epistemic]                                      M     2.1449   0.1009
C(response_condition)[T.possible]                                    M     0.3126   0.0990
C(expected_flavor)[T.epistemic]:C(response_condition)[T.possible]    M    -0.8753   0.1321
participant                                                          V    -0.3336   0.1247 0.716   0.558   0.919
item                                                                 V    -0.7230   0.1342 0.485   0.371   0.635
================================================================================================================
Parameter types are mean structure (M) and variance structure (V)
Variance parameters are modeled as log standard deviations

In [24]:
df_no_wh = df[df["response_syntax"] != "Wh-question"].copy()

model_no_wh = BinomialBayesMixedGLM.from_formula(
    "epistemic_response ~ C(expected_flavor) * C(response_condition)",
    {
        "participant": "0 + C(participant_id)",
        "item": "0 + C(item_id)"
    },
    df_no_wh
)

fit_no_wh = model_no_wh.fit_vb()

print(fit_no_wh.summary())

                                           Binomial Mixed GLM Results
================================================================================================================
                                                                  Type Post. Mean Post. SD   SD  SD (LB) SD (UB)
----------------------------------------------------------------------------------------------------------------
Intercept                                                            M    -1.3405   0.0812
C(expected_flavor)[T.epistemic]                                      M     2.0728   0.1063
C(response_condition)[T.possible]                                    M     0.4975   0.1065
C(expected_flavor)[T.epistemic]:C(response_condition)[T.possible]    M    -0.9920   0.1409
participant                                                          V    -0.2349   0.1245 0.791   0.616   1.014
item                                                                 V    -1.2946   0.1468 0.274   0.204   0.367
================================================================================================================
Parameter types are mean structure (M) and variance structure (V)
Variance parameters are modeled as log standard deviations

In [25]:
summary = (
    df_no_wh
    .groupby(
        ["expected_flavor", "response_condition"],
        observed=True
    )
    .agg(
        n=("epistemic_response", "size"),
        epistemic_percent=("epistemic_response", "mean")
    )
    .reset_index()
)

print(summary)

  expected_flavor response_condition    n  epistemic_percent
0         deontic                may  154           0.220779
1         deontic           possible  198           0.333333
2       epistemic                may  182           0.653846
3       epistemic           possible  234           0.538462

In [26]:
pivot = summary.pivot(
    index="response_condition",
    columns="expected_flavor",
    values="epistemic_percent"
)

pivot["flavor_discrimination"] = (
    pivot["epistemic"] - pivot["deontic"]
)

print(pivot)

expected_flavor      deontic  epistemic  flavor_discrimination
response_condition
may                 0.220779   0.653846               0.433067
possible            0.333333   0.538462               0.205128

In [27]:
item_analysis = df_no_wh.groupby([
    "item_id", "expected_flavor" 
    ])["epistemic_response"].mean().reset_index()

item_analysis["% may"] = df_no_wh[(df_no_wh["response_condition"] == "may")].groupby([
    "item_id", "expected_flavor" 
    ])["epistemic_response"].mean().reset_index()["epistemic_response"]

item_analysis["% possible"] = df_no_wh[(df_no_wh["response_condition"] == "possible")].groupby([
    "item_id", "expected_flavor" 
    ])["epistemic_response"].mean().reset_index()["epistemic_response"]

item_analysis["count"] = df_no_wh.groupby([
    "item_id", "expected_flavor" 
    ])["epistemic_response"].count().reset_index()["epistemic_response"]

item_analysis["may count"] = df_no_wh[(df_no_wh["response_condition"] == "may")].groupby([
    "item_id", "expected_flavor" 
    ])["epistemic_response"].count().reset_index()["epistemic_response"]

item_analysis["possible count"] = df_no_wh[(df_no_wh["response_condition"] == "possible")].groupby([
    "item_id", "expected_flavor" 
    ])["epistemic_response"].count().reset_index()["epistemic_response"]

item_analysis

/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_11301/1362970868.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  item_analysis = df_no_wh.groupby([
/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_11301/1362970868.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  item_analysis["% may"] = df_no_wh[(df_no_wh["response_condition"] == "may")].groupby([
/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_11301/1362970868.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  item_analysis["% possible"] = df_no_wh[(df_no_wh["response_condition"] == "possible")].groupby([
/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_11301/1362970868.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  item_analysis["count"] = df_no_wh.groupby([
/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_11301/1362970868.py:17: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  item_analysis["may count"] = df_no_wh[(df_no_wh["response_condition"] == "may")].groupby([
/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_11301/1362970868.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  item_analysis["possible count"] = df_no_wh[(df_no_wh["response_condition"] == "possible")].groupby([

,item_id,expected_flavor,epistemic_response,% may,% possible,count,may count,possible count
0,C1,deontic,0.411765,0.500000,0.333333,17,8,9
1,C1,epistemic,0.400000,0.333333,0.444444,15,6,9
2,C2,deontic,0.533333,0.400000,0.600000,15,5,10
3,C2,epistemic,0.352941,0.444444,0.250000,17,9,8
4,C3,deontic,0.266667,0.166667,0.333333,15,6,9
5,C3,epistemic,0.529412,0.375000,0.666667,17,8,9
6,C4,deontic,0.352941,0.444444,0.250000,17,9,8
7,C4,epistemic,0.600000,0.800000,0.500000,15,5,10
8,C5,deontic,0.294118,0.250000,0.333333,17,8,9
9,C5,epistemic,0.333333,0.333333,0.333333,15,6,9
10,C6,deontic,0.533333,0.400000,0.600000,15,5,10
11,C6,epistemic,0.470588,0.666667,0.250000,17,9,8
12,C7,deontic,0.533333,0.500000,0.555556,15,6,9
13,C7,epistemic,0.470588,0.500000,0.444444,17,8,9
14,C8,deontic,0.235294,0.222222,0.250000,17,9,8
15,C8,epistemic,0.333333,0.200000,0.400000,15,5,10
16,F1,deontic,0.218750,0.071429,0.333333,32,14,18
17,F1,epistemic,NaN,NaN,NaN,0,0,0
18,F2,deontic,NaN,NaN,NaN,0,0,0
19,F2,epistemic,0.562500,0.571429,0.555556,32,14,18
20,F3,deontic,NaN,NaN,NaN,0,0,0
21,F3,epistemic,0.531250,0.714286,0.388889,32,14,18
22,F4,deontic,0.343750,0.357143,0.333333,32,14,18
23,F4,epistemic,NaN,NaN,NaN,0,0,0
24,F5,deontic,NaN,NaN,NaN,0,0,0
25,F5,epistemic,0.687500,0.785714,0.611111,32,14,18
26,F6,deontic,NaN,NaN,NaN,0,0,0
27,F6,epistemic,0.406250,0.357143,0.444444,32,14,18
28,F7,deontic,0.437500,0.285714,0.555556,32,14,18
29,F7,epistemic,NaN,NaN,NaN,0,0,0
30,F8,deontic,NaN,NaN,NaN,0,0,0
31,F8,epistemic,0.437500,0.571429,0.333333,32,14,18
32,T1,deontic,0.235294,0.125000,0.333333,17,8,9
33,T1,epistemic,0.933333,1.000000,0.888889,15,6,9
34,T11,deontic,0.200000,0.000000,0.333333,15,6,9
35,T11,epistemic,0.764706,0.750000,0.777778,17,8,9
36,T12,deontic,0.058824,0.000000,0.125000,17,9,8
37,T12,epistemic,0.933333,1.000000,0.900000,15,5,10
38,T3,deontic,0.066667,0.000000,0.111111,15,6,9
39,T3,epistemic,0.823529,1.000000,0.666667,17,8,9
40,T5,deontic,0.176471,0.125000,0.222222,17,8,9
41,T5,epistemic,0.800000,1.000000,0.666667,15,6,9
42,T6,deontic,0.200000,0.200000,0.200000,15,5,10
43,T6,epistemic,0.705882,0.777778,0.625000,17,9,8
44,T7,deontic,0.000000,0.000000,0.000000,15,6,9
45,T7,epistemic,0.941176,1.000000,0.888889,17,8,9
46,T9,deontic,0.176471,0.125000,0.222222,17,8,9
47,T9,epistemic,0.666667,0.833333,0.555556,15,6,9

In [28]:
item_analysis.to_csv("whole_scenario_grouped_results.csv")

In [40]:
results["group"].apply(int).value_counts().reset_index().sort_values("group")

    group  count
0       1    112
13      3     28
3       5     56
16      6     28
17      9     28
5      12     56
15     13     28
9      14     56
12     17     28
10     18     28
8      19     56
2      20     56
6      21     56
7      24     56
4      25     56
11     27     28
14     30     28
1      31    112

In [ ]:
# get data for missing groups
remaining_groups = [x for x in range(1, 33) if x not in results["group"].apply(int).to_list()]
print(remaining_groups)
print(len(remaining_groups))

[2, 4, 7, 8, 10, 11, 15, 16, 22, 23, 26, 28, 29, 32]
14

In [50]:
df = pd.read_csv("../norming_stimulus/whole_scenario_stimulus.csv")
df_remaining = df[df["group"].isin(remaining_groups)].reset_index()

df_remaining.head()

,index,item_id,response_type,temporal_code,context_order,response_polarity,phase,domain,temporal_orientation,order,...,whole_scenario_question,context_order_code,group,response_code,scale_code,scale_order,list_rotation,polarity_rotation,left_interpretation,right_interpretation
0,28,C1,may,0,0,negative,Critical Test,Zoo animal-care room,future eventive,N-E-D,...,What is the speaker talking about?,0,2,0,0,deontic-epistemic,0,1,The rules or permissions,The available information
1,29,C2,may,0,1,negative,Critical Test,University observatory,future eventive,N-D-E,...,What is the speaker talking about?,1,2,0,0,deontic-epistemic,0,1,The rules or permissions,The available information
2,30,C3,may,1,0,positive,Critical Test,Student film studio,past perfect,N-E-D,...,What is the speaker talking about?,0,2,0,0,deontic-epistemic,0,1,The rules or permissions,The available information
3,31,C4,may,1,1,negative,Critical Test,Hotel rooftop lounge,present stative,N-D-E,...,What is the speaker talking about?,1,2,0,0,deontic-epistemic,0,1,The rules or permissions,The available information
4,32,C5,may,0,0,positive,Critical Test,Aquatic center diving area,future eventive,N-E-D,...,What is the speaker talking about?,0,2,0,0,deontic-epistemic,0,1,The rules or permissions,The available information

In [51]:
df_remaining.to_csv("../norming_stimulus/whole_scenario_stimulus_remaining.csv")