In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("context_only_results_force.csv")
print(df.shape)
df.head()

(3176, 24)

,Results.reception.time,MD5.hash.of.participant.s.IP.address,Controller.name,Order.number.of.item,Inner.element.number,Label,Latin.Square.Group,PennElementType,PennElementName,Parameter,...,item_id,judgment_force,modal_polarity,context,context_only_question,domain,temporal_orientation,order,group,Comments
0,1793047291,18801d8a10eeb55a6b338cae4ac11f0c,PennController,2,0,consent,NaN,PennController,0,_Header_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1793047291,18801d8a10eeb55a6b338cae4ac11f0c,PennController,2,0,consent,NaN,PennController,0,_Header_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1793047291,18801d8a10eeb55a6b338cae4ac11f0c,PennController,2,0,consent,NaN,PennController,0,_Trial_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1793047291,18801d8a10eeb55a6b338cae4ac11f0c,PennController,2,0,consent,NaN,PennController,0,_Trial_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1793047291,18801d8a10eeb55a6b338cae4ac11f0c,PennController,3,0,background,NaN,PennController,1,_Header_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
results = df[(df["Label"] == "experimental-trial") & (df["Parameter"] == "Selection")]
results.head()

,Results.reception.time,MD5.hash.of.participant.s.IP.address,Controller.name,Order.number.of.item,Inner.element.number,Label,Latin.Square.Group,PennElementType,PennElementName,Parameter,...,item_id,judgment_force,modal_polarity,context,context_only_question,domain,temporal_orientation,order,group,Comments
53,1793047291,18801d8a10eeb55a6b338cae4ac11f0c,PennController,31,0,experimental-trial,NaN,Selector,selection,Selection,...,T6,possibility,1,One benefit of Maya's silver ticket is that sh...,According to the story%2C is Maya <b>permitted...,Theater,future eventive,D-N,1.0,yes;no
59,1793047291,18801d8a10eeb55a6b338cae4ac11f0c,PennController,28,0,experimental-trial,NaN,Selector,selection,Selection,...,T3,possibility,1,Nora is at the community center right now. The...,According to the story%2C is it <b>possible</b...,Community center,past perfect / present progressive or stative,N-E,1.0,yes;no
65,1793047291,18801d8a10eeb55a6b338cae4ac11f0c,PennController,29,0,experimental-trial,NaN,Selector,selection,Selection,...,T4,possibility,1,Kai is traveling home tomorrow. Kai's flexible...,According to the story%2C is Kai <b>permitted<...,Train,future eventive,N-D,1.0,yes;no
71,1793047291,18801d8a10eeb55a6b338cae4ac11f0c,PennController,15,0,experimental-trial,NaN,Selector,selection,Selection,...,C5,possibility,1,Chloe is returning for swim practice tomorrow....,According to the story%2C is Chloe <b>permitte...,Aquatic center diving area,future eventive,N-Nec-P,1.0,yes;no
77,1793047291,18801d8a10eeb55a6b338cae4ac11f0c,PennController,33,0,experimental-trial,NaN,Selector,selection,Selection,...,T8,necessity,0,Sofia is taking a ferry tomorrow for a family ...,According to the story%2C is Sofia <b>required...,Ferry,future eventive,N-D,1.0,yes;no

In [4]:
results["phase"] = results["item_id"].apply(lambda x: x[0])
results["phase"]

/var/folders/lq/kd3wh6952vg99n5ppf4srz9w0000gn/T/ipykernel_11508/2704397132.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results["phase"] = results["item_id"].apply(lambda x: x[0])

53      T
59      T
65      T
71      C
77      T
       ..
3144    T
3150    F
3156    C
3162    C
3168    C
Name: phase, Length: 384, dtype: object

In [5]:
results["group"].value_counts()

group
1.0    48
2.0    48
3.0    48
4.0    48
5.0    48
6.0    48
7.0    48
8.0    48
Name: count, dtype: int64

In [ ]:
results.columns

Index(['Results.reception.time', 'MD5.hash.of.participant.s.IP.address',
       'Controller.name', 'Order.number.of.item', 'Inner.element.number',
       'Label', 'Latin.Square.Group', 'PennElementType', 'PennElementName',
       'Parameter', 'Value', 'EventTime', 'PROLIFIC_ID', 'rt', 'item_id',
       'judgment_force', 'modal_polarity', 'context', 'context_only_question',
       'domain', 'temporal_orientation', 'order', 'group', 'Comments',
       'phase'],
      dtype='object')

In [8]:
results.groupby(["judgment_force", "modal_polarity"])["Value"].value_counts()

judgment_force  modal_polarity  Value
necessity       -1              no        69
                                yes       11
                0               no        81
                                yes       15
                1               yes       11
                                no         5
possibility     -1              no        12
                                yes        4
                1               yes      146
                                no        30
Name: count, dtype: int64

In [9]:
results.groupby(["judgment_force", "modal_polarity", "phase"])["Value"].value_counts()

judgment_force  modal_polarity  phase  Value
necessity       -1              C      no       57
                                       yes       7
                                F      no       12
                                       yes       4
                0               T      no       81
                                       yes      15
                1               F      yes      11
                                       no        5
possibility     -1              F      no       12
                                       yes       4
                1               C      yes      54
                                       no       10
                                F      yes      13
                                       no        3
                                T      yes      79
                                       no       17
Name: count, dtype: int64

In [11]:
results.groupby(["item_id", "judgment_force", "modal_polarity"])["Value"].value_counts().reset_index().to_csv("context_only_grouped_results_force.csv")