In [5]:
import pandas as pd

In [ ]:
df = pd.read_csv("context_only_results.csv")
print(df.shape)
df.head()

(3267, 24)

,Results.reception.time,MD5.hash.of.participant.s.IP.address,Controller.name,Order.number.of.item,Inner.element.number,Label,Latin.Square.Group,PennElementType,PennElementName,Parameter,...,item_id,judgement_flavour,modal_possibility,context,context_only_question,domain,temporal_orientation,order,group,Comments
0,1791345532,b3926bcf883fb8dc77fc62560bad6721,PennController,2,0,consent,NaN,PennController,0,_Trial_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1791345532,b3926bcf883fb8dc77fc62560bad6721,PennController,2,0,consent,NaN,PennController,0,_Header_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1791345532,b3926bcf883fb8dc77fc62560bad6721,PennController,2,0,consent,NaN,PennController,0,_Header_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1791345532,b3926bcf883fb8dc77fc62560bad6721,PennController,2,0,consent,NaN,PennController,0,_Trial_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1791345532,b3926bcf883fb8dc77fc62560bad6721,PennController,3,0,background,NaN,PennController,1,_Trial_,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
results = df[(df["Label"] == "experimental-trial") & (df["Parameter"] == "Selection")]
results.head()

,Results.reception.time,MD5.hash.of.participant.s.IP.address,Controller.name,Order.number.of.item,Inner.element.number,Label,Latin.Square.Group,PennElementType,PennElementName,Parameter,...,item_id,judgement_flavour,modal_possibility,context,context_only_question,domain,temporal_orientation,order,group,Comments
59,1791345532,b3926bcf883fb8dc77fc62560bad6721,PennController,20,0,experimental-trial,NaN,Selector,selection,Selection,...,F1,Deontic,1.0,Tessa's clinic pass includes use of the warm-u...,According to the <b>rules or permissions</b> d...,Ice rink warm-up studio,future eventive,D-N-E,1.0,yes;no;third
65,1791345532,b3926bcf883fb8dc77fc62560bad6721,PennController,29,0,experimental-trial,NaN,Selector,selection,Selection,...,T3,Epistemic,1.0,Nora is at the community center right now. The...,Based on the <b>information</b> described in t...,Community center,past perfect / present progressive or stative,N-E,1.0,yes;no;third
71,1791345532,b3926bcf883fb8dc77fc62560bad6721,PennController,28,0,experimental-trial,NaN,Selector,selection,Selection,...,T2,Deontic,0.0,Priya's classmate knows she is in either the r...,According to the <b>rules or permissions</b> d...,Library rooms,past perfect / present progressive or stative,E-N,1.0,yes;no;third
77,1791345532,b3926bcf883fb8dc77fc62560bad6721,PennController,27,0,experimental-trial,NaN,Selector,selection,Selection,...,T12,Deontic,0.0,Daniel is doing an experiment right now. Danie...,According to the <b>rules or permissions</b> d...,College lab,past perfect / present progressive or stative,N-E,1.0,yes;no;third
83,1791345532,b3926bcf883fb8dc77fc62560bad6721,PennController,35,0,experimental-trial,NaN,Selector,selection,Selection,...,T9,Deontic,0.0,Mateo arrived at a music festival earlier toni...,According to the <b>rules or permissions</b> d...,Festival gate,past perfect / present progressive or stative,N-E,1.0,yes;no;third

In [13]:
results.groupby(["judgement_flavour", "modal_possibility"])["Value"].value_counts()

judgement_flavour  modal_possibility  Value
Deontic            -1.0               no       39
                                      yes       7
                                      third     2
                   0.0                third    27
                                      yes      16
                                      no        5
                   1.0                yes      77
                                      no       13
                                      third     6
Epistemic          -1.0               no       26
                                      yes      22
                   0.0                yes      43
                                      no        5
                   1.0                yes      44
                                      no        4
Name: count, dtype: int64

In [17]:
results.groupby(["item_id", "judgement_flavour", "modal_possibility"])["Value"].value_counts().reset_index().to_csv("grouped_results.csv")